



clear all
close all




% Observations
load S.mat; cond=4;                                                         % Load specific observations
o1=S(cond).O1(1,:);                                                         % Positive to negative to positive again
o1=[o1 o1];                                                                 % Double the size of o1 to get more observations
% plot(o1);                                                                 % Plot (normally distributed) observations

% Lenghts for for loops
NOs = max(o1);                                                              %   10    o1   outcomes
NS1 = 5;                                                                    %    5    S1   states (priors)
NM1 = 4;                                                                    %    4    M1   models (hyperpriors)
Tau = 2;                                                                    %    2   Tau   observations per trial
T =  length(o1)/2;                                                          %   80     T   trials
Nobs = length(o1);                                                          %  160    O1   observations (behaviours)

% Key parameters
eta   = [0.00  1.00  0.00  0.00];                                           % Learning rate (high = fast update of Dirichlet priors)
omega = [1.00  0.75  1.00  1.00];                                           % Forgetting rate (high = slow forgetting of Dirichlet priors)
ps1   = [1.45  1.00  1.45  1.00];                                           % Precision of P(s1|m1): Higher = more internal mentalizing
po1   =  0.40;                                                              % Precision of P(o1|s1): Higher = more external mentalizing




% Hyperpriors: priors of mental states: P(s1|m1)
% (how mental states are generated by model of Self/Other)
S1 = [0 3 5 7 10];                                                          % Values x at which to evaluate probability density function
prior_s1_m1(:, 1 ) = normpdf(S1,  1,  1/ps1(1));                            % Discrete Gaussian with μ=01 & σ=0.7, reflecting states under  NEGATIVE  mental model
prior_s1_m1(:, 2 ) = normpdf(S1,  5,  1/ps1(2));                            % Discrete Gaussian with μ=05 & σ=1.0, reflecting states under   NORMAL   mental model
prior_s1_m1(:, 3 ) = normpdf(S1,  9,  1/ps1(3));                            % Discrete Gaussian with μ=09 & σ=0.7, reflecting states under  POSITIVE  mental model
prior_s1_m1(:, 4 ) = ones(1, 5, 1/ps1(4));                                  % Discrete distribution with only 1s,  reflecting states under   EMPTY    mental model
% plot(prior_s1_m1)                                                         % Plot NORMAL (bell curve), BAD (positively skewed), GOOD (negatively skewed), and EMPTY (flat)

% Add concentration parameters
% (which encode how rigid a belief is)
prior_s1_m1(:, 1 ) = prior_s1_m1(:, 1 )*100000;                             % Positively Skewed   (Negative)   &  Rigid Hyperprior (based on 100000 concentration parameters)
prior_s1_m1(:, 2 ) = prior_s1_m1(:, 2 )*100;                                % Gaussian           (Integrated)  &  Flexible Hyperprior (based on 100 concentration parameters)
prior_s1_m1(:, 3 ) = prior_s1_m1(:, 3 )*100000;                             % Negatively Skewed   (Positive)   &  Rigid Hyperprior (based on 100000 concentration parameters)
prior_s1_m1(:, 4 ) = prior_s1_m1(:, 4 )*1;                                  % Flat                  (Empty)    &  Plastic Hyperprior (based on zero concentration parameters)

% Normalize priors (to ensure probabilities sum to 1)
% (by dividing each prior with the sum of its states)
P_S1_M1(:, 1 ) = prior_s1_m1(:, 1 )./sum(prior_s1_m1(:, 1 ));               % P(S1|M1) = States under  NEGATIVE  model
P_S1_M1(:, 2 ) = prior_s1_m1(:, 2 )./sum(prior_s1_m1(:, 2 ));               % P(S1|M1) = States under INTEGRATED model
P_S1_M1(:, 3 ) = prior_s1_m1(:, 3 )./sum(prior_s1_m1(:, 3 ));               % P(S1|M1) = States under  POSITIVE  model
P_S1_M1(:, 4 ) = prior_s1_m1(:, 4 )./sum(prior_s1_m1(:, 4 ));               % P(S1|M1) = States under    EMPTY   model

% Initialize distributions
% for trial-trial inferences
P_S1_M1_O =  nan(NS1, NM1, T);                                              % 5x4x40   matrix  encoding P(S1|M1,O) over T=40 trials
P_S1_O    =  nan(NS1, T);                                                   % 5x40     matrix  encoding P(S1|O)    over T=40 trials
P_M1_O    =  nan(NM1, T);                                                   % 4x40     matrix  encoding P(M1|O)    over T=40 trials
Pr        =  nan(NS1, NM1);                                                 % 5x4      matrix  encoding P(S1|M1)
P_O_SM    =  nan(NS1, NM1);                                                 % 5x4      matrix  encoding P(O1|S1,M1)
P_O1_S1   =  nan(NOs, NS1);                                                 % 10x5     matrix  encoding P(O1|S1) (see next %)

% Get likelihood: P(O1|S1)
O1 = 1:1:max(o1);                                                           % Outcomes [1 2 3 4 5 6 7 8 9 10]
for s1=1:NS1                                                                % For loop to create the (10x5) likelihood matrix: P(O1|S1)
    pdf = normpdf(O1, S1(s1), 1/po1);                                       % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
    P_O1_S1(:,s1) = pdf./sum(pdf);                                          % Normalize Gaussian by dividing each of its columns with its SUM
end                                                                         % End result is 10x5 matrix representing all state-outcome mappings




o=1;                                                                        % Indicator of which observation the agent experiences at trial t, time tau
i=1;                                                                        % Indicator of Figure position (see PLOTTING section at line 182)

for model=1:5
    
    
    
    if model==1                                                             % IF function to run through five models
       FF=figure;                                                           % Open up one and only figure in the first iteration
       % FF = figure('Position', [100, 100, 1550, 1100]);                   % Use this to print out figure in a higher resolution
       prior_m1 = [0 1 0 0];                                                % This allows only the  NORMAL  mental model to be active
       colour='cyan';
    
    elseif model==2
       prior_m1 = [1 0 0 0];                                                % This allows only the NEGATIVE mental model to be active
       colour = [0.1000 0.4470 0.9000];
    
    elseif model==3
       prior_m1 = [0 0 1 0];                                                % This allows only the POSITIVE mental model to be active
       colour = [0.95 0 0];
    
    elseif model==4
       prior_m1 = [1 0 1 0];                                                % This allows both the NEGATIVE & POSITIVE models to be active (creating a SPLIT mental model)
       colour='black';
    
    else
       prior_m1 = [0 0 0 1];                                                % This allows only the EMPTY mental model to be active
       colour='yellow';
    
    end
    
    P_M1(:,1) = prior_m1./sum(prior_m1);                                    % Normalize distribution of mental model: P(M1)
    
    
    
    for t=1:T                                                               % For loop from t=1 to T=40 (number of trials)
        
        
        % -------------------------------------------------------------- % 
        % ------------------------- INFERENCE -------------------------- % 
        % -------------------------------------------------------------- % 
        %  Inference involves inverting the model by looping over states % 
        % -------------------------------------------------------------- % 
        for tau=1:Tau                                                       % For loop from tau=1 to Tau=2 (number of observations per trial)
            
            for m1=1:NM1                                                    % For loop from m1=1 to NM1=4 (number of state configurations / hyperpriors)
                
                % PRIORS
                if tau==1                                                   % If-then function to create priors of states based on mental models: P(S1|M1)
                   Pr(:, m1) = P_S1_M1(:, m1, t)*P_M1(m1, t);               % For the first observation (at t=1 & tau=1) the prior is P(S1|M1)*P(M1)
                else                                                        % For all other (tau) observations (in all other trials), 
                   Pr(:, m1) = P_S_O(:, m1);                                % the prior is simply the previous posterior: P(S1,M1|O).
                end                                                         % Pr = Prior = 5x4 matrix = how probable each state is under a given mental model
                
                % LIKELIHOODS
                P_O_SM(:, m1) = P_O1_S1(o1(o), :);                          % P(O1_tau|S1) = 5x4 matrix = How likely each state is given a particular observation
            
            end
            
            % BAYESIAN INVERSION                                            % Use Bayes' rule to invert generative model and obtain P(S1,M1|O)
            P_J   = Pr.*P_O_SM;                                             % Bayes numerator: Joint probability: P(O1,S1,M1)
            Po    = sum(P_J(:));                                            % Bayes denominator: Marinal probability: P(O)
            P_S_O = P_J./Po;                                                % Posterior: P(S1,M1|O) = Joint / Marginal = 10x4 matrix
            
            o=o+1;                                                          % Add 1 to the variable that indicates which observation is experienced at trial T, time tau
        
        end
        
        % Marginal posteriors at the end of the trial
        P_S1_M1_O(:,:,t) = squeeze(P_S_O);                                  % Squeeze the posterior at time t into a placeholder variable
        P_S1_O(:,t)      = sum(P_S_O,2);                                    % Sum rows of P_S_O (prob of states given observations across all models)
        P_M1_O(:,t)      = squeeze(sum(P_S_O,1));                           % Sum columns of P_S_O (prob of each model being endorsed based on state likelihood)
        
        
        % -------------------------------------------------------------- % 
        % ------------------------- LEARNING --------------------------- % 
        % -------------------------------------------------------------- % 
        %  Learning involves updating Dirichlet concentration parameters % 
        % -------------------------------------------------------------- % 
        
        % Update concentration parameters of Dirichlet priors
        prior_s1_m1(:,1) = omega(1)*prior_s1_m1(:,1) + ...                  % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                           eta(1)*P_S1_M1_O(:,1,t);                         
        prior_s1_m1(:,2) = omega(2)*prior_s1_m1(:,2) + ...                  % Dirichlet prior denoting P(S1|M1=INTEGRATED)
                           eta(2)*P_S1_M1_O(:,2,t);                         
        prior_s1_m1(:,3) = omega(3)*prior_s1_m1(:,3) + ...                  % Dirichlet prior denoting P(S1|M1=POSITIVE)
                           eta(3)*P_S1_M1_O(:,3,t);                         
        prior_s1_m1(:,4) = omega(4)*prior_s1_m1(:,4) + ...                  % Dirichlet prior denoting P(S1|M1=EMPTY)
                           eta(4)*P_S1_M1_O(:,4,t);                         
        prior_m1         = omega(2)*prior_m1 + ...                          % Dirichlet prior denoting P(M1)
                           eta(2)*P_M1_O(:,t)';                             
        
        % Normalise priors
        P_S1_M1(:, 1, t+1) = prior_s1_m1(:, 1)/sum(prior_s1_m1(:,1),1);     % Column 1 of P(S1|M1=NEGATIVE)   divided by its sum
        P_S1_M1(:, 2, t+1) = prior_s1_m1(:, 2)/sum(prior_s1_m1(:,2),1);     % Column 2 of P(S1|M1=INTEGRATED) divided by its sum
        P_S1_M1(:, 3, t+1) = prior_s1_m1(:, 3)/sum(prior_s1_m1(:,3),1);     % Column 3 of P(S1|M1=POSITIVE)   divided by its sum
        P_S1_M1(:, 4, t+1) = prior_s1_m1(:, 4)/sum(prior_s1_m1(:,4),1);     % Column 4 of P(S1|M1=EMPTY)      divided by its sum
        P_M1(:, t+1)       = prior_m1./sum(prior_m1);                       % Column 1 of P(M1)               divided by its sum
        
        
    end
    
    
    
    % ------------------------------------------------------------------ % 
    % --------------------------- PLOTTING ----------------------------- % 
    % ------------------------------------------------------------------ % 
    %                Plotting iteratively all five models                % 
    % ------------------------------------------------------------------ % 
    
    % Prepare variables for plotting
    P_S1_O_plot = P_S1_O;                                                   % New placeholder variable for P(S1|O1)
    
    % Expand posteriors for plotting purposes
    o=1;                                                                    % Indicator for observation
    for t=1:T                                                               % For loop across all time points T=80
        for tau=1:Tau                                                       % For loop across all trials Tau=2
        P_S1_O_plot(:,o)        = P_S1_O(:,t);                              % Turn ts into os for P(S1|O1)
        o=o+1;                                                              % Add 1 to observation
        end                                                                 
    end                                                                     
    
    % Posterior over outcomes
    Xo=P_O1_S1;                                                             % P(O1|S1)
    for o=1:Nobs                                                            % For loop from o=1 to all observations=160
        Xo(:,o) = P_O1_S1*P_S1_O_plot(:,o);                                 % Marginalise over s1: Likelihood (P(O1|S1)) * Marginal Posterior (states after obs: P(S1|O1))
    end
    
    % Find posterior prediction
    a=NaN(1,160);                                                           % Initialize a: posterior prediction
    for o=1:Nobs                                                            % For loop across all observations = 160
        a(:,o) = find(Xo(:,o)==max(Xo(:,o)));                               % Find location of maximal Xo in each column (trial)
    end                                                                     % End result = 1x160 indicating posterior predictions
    
    % PLOT models
    subplot(5,3,i);                                                         % Subplot: 5 rows, 3 columns, i=first (left) column
    if model==1
       h=bar(P_S1_M1(:,2));                                                 
       title('(A) Integrated Model (Gaussian distribution: π_{m}=1, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==2
       h=bar(P_S1_M1(:,1));
       title('(B) Negative Model (Left skewed distribution: π_{m}=1.4, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==3
       h=bar(P_S1_M1(:,3));
       title('(C) Positive Model (Right skewed distribution: π_{m}=1.4, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==4
       h=bar(P_S1_M1(:,1)); h.FaceColor=colour; hold on
       h=bar(P_S1_M1(:,3));
       title('(D) Split Model (Left & Right skewed distributions: π_{m}=1.4, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    else
       h=bar(P_S1_M1(:,4));
       title('(E) Empty Model (Flat distribution: π_{m}=0, π_{ο}=0.4)', ...
             'FontSize', 8.5)
       xlabel('\fontsize{8.5} States')
    end
    ylim([0 1]); 
    h.FaceColor=colour;
    ylabel('\fontsize{8.5} P(S1|M1)')
    
    hold on
    
    % PLOT posteriors
    subplot(5,3,[i+1 i+2]);                                                 % Subplot: 5 rows, 3 columns, i=two (right) columns
    plot(o1,'ko', 'Color','k', ...
        'Markersize',8, ...
         MarkerFaceColor=[.8 .8 .8]); hold on;
    plot(a(:,:),'ko', 'Color','k', 'Markersize',6, MarkerFaceColor=colour); 
    hold on; ylim([0 11]);
    
    if model==1
       title('(A) (Internal) Mental Inferences under integrated model (cyan circles) and normal observations (grey circles)')
    elseif model==2
       title('(B) (Internal) Mental Inferences under negative model (blue circles) and normal observations (grey circles)')
    elseif model==3
       title('(C) (Internal) Mental Inferences under positive model (red circles) and normal observations (grey circles)')
    elseif model==4
       title('(D) (Internal) Mental Inferences under split model (black circles) and normal observations (grey circles)')
    else
       title('(E) (External) Mental Inferences under empty model (yellow circles) and normal observations (grey circles)')
       xlabel('\fontsize{8.5} Trial')
    end
    
    ylabel('\fontsize{8.5} Observation')
    
    hold on
    
    i = i+3;                                                                % Add 3 to i to move to next row (after having filled 3 columns)
    o = 1;                                                                  % Initialize observations (for the next model)
    
    
end

% Get current figure handle
fig = gcf;

% Set figure units to inches
fig.Units = 'inches';
fig.PaperUnits = 'inches';

% Define desired width and height (e.g., 14x10 inches)
width = 14;
height = 10;

% Adjust on-screen figure size
fig.Position(3:4) = [width, height];

% Configure paper settings
fig.PaperPositionMode = 'manual';
fig.PaperPosition = [0 0 width height];
fig.PaperSize = [width height];

% Set background color to white
fig.Color = 'white';            % White background color
fig.InvertHardcopy = 'off';     % Maintain existing colors

% Save as PDF with vector renderer
print(fig, 'Figure 3.pdf', '-dpdf', '-painters');

