



clear all
close all




% Observations
load S.mat; cond=2;                                                         % Load specific observations
o1=S(cond).O1(1,:);                                                         % Positive to negative to positive again
o1=[o1 o1];                                                                 % Double the size of o1 to get more observations
% plot(o1);                                                                 % Plot (normally distributed) observations

% Lenghts for for loops
NOs = max(o1);                                                              %   10    o1   outcomes
NS1 = 5;                                                                    %    5    S1   states (priors)
NM1 = 4;                                                                    %    4    M1   models (hyperpriors)
Tau = 2;                                                                    %    2   Tau   observations per trial
T =  length(o1)/2;                                                          %   80     T   trials
Nobs = length(o1);                                                          %  160    O1   observations (behaviours)

% Key parameters
eta   = 0.60;                                                               % Learning rate (high = fast update of Dirichlet priors)
omega = 1.00 ;                                                              % Forgetting rate (high = slow forgetting of Dirichlet priors)
ps1   = [0.60  1.20  0.60  1.00];                                           % Precision of P(s1|m1): Higher = more internal mentalizing
po1   =  0.40;                                                              % Precision of P(o1|s1): Higher = more external mentalizing




% Hyperpriors: priors of mental states: P(s1|m1)
% (how mental states are generated by model of Self/Other)
S1 = [0 3 5 7 10];                                                          % Values x at which to evaluate probability density function
prior_s1_m1(:, 1 ) = normpdf(S1,  1,  1/ps1(1));                            % Discrete Gaussian with μ=01 & σ=0.6, reflecting states under  NEGATIVE  mental model
prior_s1_m1(:, 2 ) = normpdf(S1,  1,  1/ps1(2));                            % Discrete Gaussian with μ=05 & σ=1.2, reflecting states under   NORMAL   mental model
prior_s1_m1(:, 3 ) = normpdf(S1,  1,  1/ps1(3));                            % Discrete Gaussian with μ=09 & σ=0.6, reflecting states under  POSITIVE  mental model
prior_s1_m1(:, 4 ) = ones(1, 5, 1/ps1(4));                                  % Discrete distribution with only 1s,  reflecting states under   EMPTY    mental model
prior_s1_m1(:, 4 ) = ones(1, 5, 1/ps1(4));                                  % Discrete distribution with only 1s,  reflecting states under   EMPTY    mental model
% plot(prior_s1_m1)                                                         % Plot NORMAL (bell curve), BAD (positively skewed), GOOD (negatively skewed), and EMPTY (flat)

% Add concentration parameters
% (which encode how rigid a belief is)
prior_s1_m1(:, 1 ) = prior_s1_m1(:, 1 )*140;                                % Flexible prior (π=0.6 & based on few concentration parameters)
prior_s1_m1(:, 2 ) = prior_s1_m1(:, 2 )*10000;                              % Rigid prior (π=1.20 & based on lots of concentration parameters)
prior_s1_m1(:, 3 ) = prior_s1_m1(:, 3 )*20;                                 % Flexible prior (π=0.6 & based on very few concentration parameters)
prior_s1_m1(:, 4 ) = prior_s1_m1(:, 4 )*1;                                  % Flat prior (not used in this simulation)

% Normalize priors (to ensure probabilities sum to 1)
% (by dividing each prior with the sum of its states)
P_S1_M1(:, 1 ) = prior_s1_m1(:, 1 )./sum(prior_s1_m1(:, 1 ));               % P(S1|M1) = States under  NEGATIVE  model
P_S1_M1(:, 2 ) = prior_s1_m1(:, 2 )./sum(prior_s1_m1(:, 2 ));               % P(S1|M1) = States under INTEGRATED model
P_S1_M1(:, 3 ) = prior_s1_m1(:, 3 )./sum(prior_s1_m1(:, 3 ));               % P(S1|M1) = States under  POSITIVE  model
P_S1_M1(:, 4 ) = prior_s1_m1(:, 4 )./sum(prior_s1_m1(:, 4 ));               % P(S1|M1) = States under    EMPTY   model

% Initialize distributions
% for trial-trial inferences
P_S1_M1_O =  nan(NS1, NM1, T);                                              % 5x4x40   matrix  encoding P(S1|M1,O) over T=40 trials
P_S1_O    =  nan(NS1, T);                                                   % 5x40     matrix  encoding P(S1|O)    over T=40 trials
P_M1_O    =  nan(NM1, T);                                                   % 4x40     matrix  encoding P(M1|O)    over T=40 trials
Pr        =  nan(NS1, NM1);                                                 % 5x4      matrix  encoding P(S1|M1)
P_O_SM    =  nan(NS1, NM1);                                                 % 5x4      matrix  encoding P(O1|S1,M1)
P_O1_S1   =  nan(NOs, NS1);                                                 % 10x5     matrix  encoding P(O1|S1) (see next %)

% Get likelihood: P(O1|S1)
O1 = 1:1:max(o1);                                                           % Outcomes [1 2 3 4 5 6 7 8 9 10]
% for s1=1:NS1                                                                % For loop to create the (10x5) likelihood matrix: P(O1|S1)
%     pdf = normpdf(O1, S1(s1), 1/po1(i));                                       % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
%     P_O1_S1(:,s1) = pdf./sum(pdf);                                          % Normalize Gaussian by dividing each of its columns with its SUM
% end                                                                         % End result is 10x5 matrix representing all state-outcome mappings





o=1;                                                                        % Indicator of which observation the agent experiences at trial t, time tau
i=1;                                                                        % Indicator of Figure position (see PLOTTING section at line 182)

for model=1:3
    
    
    
    if model==1                                                             % IF function to run through five models
       FF=figure;                                                           % Open up one and only figure in the first iteration
       % FF = figure('Position', [100, 100, 1550, 1100]);                   % Use this to print out figure in a higher resolution
       prior_m1 = [1 0 0 0];                                                % This allows only the  NORMAL  mental model to be active
       
       for s1=1:NS1                                                         % For loop to create the (10x5) likelihood matrix: P(O1|S1)
           pdf = normpdf(O1, S1(s1), 1/0.6);                                % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
           P_O1_S1(:,s1) = pdf./sum(pdf);                                   % Normalize Gaussian by dividing each of its columns with its SUM
       end                                                                  % End result is 10x5 matrix representing all state-outcome mappings
    
    
    elseif model==2
       prior_m1 = [0 1 0 0];                                                % This allows only the NEGATIVE mental model to be active
       
       for s1=1:NS1                                                         % For loop to create the (10x5) likelihood matrix: P(O1|S1)
           pdf = normpdf(O1, S1(s1), 1/0.6);                                % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
           P_O1_S1(:,s1) = pdf./sum(pdf);                                   % Normalize Gaussian by dividing each of its columns with its SUM
       end                                                                  % End result is 10x5 matrix representing all state-outcome mappings
    
    
    elseif model==3
       prior_m1 = [0 0 1 0];                                                % This allows only the POSITIVE mental model to be active
       
       for s1=1:NS1                                                         % For loop to create the (10x5) likelihood matrix: P(O1|S1)
           pdf = normpdf(O1, S1(s1), 1/1.2);                                % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
           P_O1_S1(:,s1) = pdf./sum(pdf);                                   % Normalize Gaussian by dividing each of its columns with its SUM
       end                                                                  % End result is 10x5 matrix representing all state-outcome mappings
    
    
    end
    
    P_M1(:,1) = prior_m1./sum(prior_m1);                                    % Normalize distribution of mental model: P(M1)
    
    
    
    for t=1:T                                                               % For loop from t=1 to T=40 (number of trials)
        
               
        % -------------------------------------------------------------- % 
        % ------------------------- INFERENCE -------------------------- % 
        % -------------------------------------------------------------- % 
        %  Inference involves inverting the model by looping over states % 
        % -------------------------------------------------------------- % 
        for tau=1:Tau                                                       % For loop from tau=1 to Tau=2 (number of observations per trial)
            
            for m1=1:NM1                                                    % For loop from m1=1 to NM1=4 (number of state configurations / hyperpriors)
                
                % PRIORS
                if tau==1                                                   % If-then function to create priors of states based on mental models: P(S1|M1)
                   Pr(:, m1) = P_S1_M1(:, m1, t)*P_M1(m1, t);               % For the first observation (at t=1 & tau=1) the prior is P(S1|M1)*P(M1)
                else                                                        % For all other (tau) observations (in all other trials), 
                   Pr(:, m1) = P_S_O(:, m1);                                % the prior is simply the previous posterior: P(S1,M1|O).
                end                                                         % Pr = Prior = 5x4 matrix = how probable each state is under a given mental model
                
                % LIKELIHOODS
                P_O_SM(:, m1) = P_O1_S1(o1(o), :);                          % P(O1_tau|S1) = 5x4 matrix = How likely each state is given a particular observation
            
            end
            
            % BAYESIAN INVERSION                                            % Use Bayes' rule to invert generative model and obtain P(S1,M1|O)
            P_J   = Pr.*P_O_SM;                                             % Bayes numerator: Joint probability: P(O1,S1,M1)
            Po    = sum(P_J(:));                                            % Bayes denominator: Marinal probability: P(O)
            P_S_O = P_J./Po;                                                % Posterior: P(S1,M1|O) = Joint / Marginal = 10x4 matrix
            
            o=o+1;                                                          % Add 1 to the variable that indicates which observation is experienced at trial T, time tau
        
        end
        
        % Marginal posteriors at the end of the trial
        P_S1_M1_O(:,:,t) = squeeze(P_S_O);                                  % Squeeze the posterior at time t into a placeholder variable
        P_S1_O(:,t)      = sum(P_S_O,2);                                    % Sum rows of P_S_O (prob of states given observations across all models)
        P_M1_O(:,t)      = squeeze(sum(P_S_O,1));                           % Sum columns of P_S_O (prob of each model being endorsed based on state likelihood)
        
        
        
        % -------------------------------------------------------------- % 
        % ------------------------- LEARNING --------------------------- % 
        % -------------------------------------------------------------- % 
        %  Learning involves updating Dirichlet concentration parameters % 
        % -------------------------------------------------------------- % 
        
        % Update concentration parameters of Dirichlet priors
        prior_s1_m1(:,1) = omega*prior_s1_m1(:,1) + ...                     % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                           eta*P_S1_M1_O(:,1,t);                         
        prior_s1_m1(:,2) = omega*prior_s1_m1(:,2) + ...                     % Dirichlet prior denoting P(S1|M1=INTEGRATED)
                           eta*P_S1_M1_O(:,2,t);                         
        prior_s1_m1(:,3) = omega*prior_s1_m1(:,3) + ...                     % Dirichlet prior denoting P(S1|M1=POSITIVE)
                           eta*P_S1_M1_O(:,3,t);                         
        prior_s1_m1(:,4) = omega*prior_s1_m1(:,4) + ...                     % Dirichlet prior denoting P(S1|M1=EMPTY)
                           eta*P_S1_M1_O(:,4,t);                         
        prior_m1         = omega*prior_m1 + ...                             % Dirichlet prior denoting P(M1)
                           eta*P_M1_O(:,t)';                             
        
        % Normalise priors
        P_S1_M1(:, 1, t+1) = prior_s1_m1(:, 1)/sum(prior_s1_m1(:,1),1);     % Column 1 of P(S1|M1=NEGATIVE)   divided by its sum
        P_S1_M1(:, 2, t+1) = prior_s1_m1(:, 2)/sum(prior_s1_m1(:,2),1);     % Column 2 of P(S1|M1=INTEGRATED) divided by its sum
        P_S1_M1(:, 3, t+1) = prior_s1_m1(:, 3)/sum(prior_s1_m1(:,3),1);     % Column 3 of P(S1|M1=POSITIVE)   divided by its sum
        P_S1_M1(:, 4, t+1) = prior_s1_m1(:, 4)/sum(prior_s1_m1(:,4),1);     % Column 4 of P(S1|M1=EMPTY)      divided by its sum
        P_M1(:, t+1)       = prior_m1./sum(prior_m1);                       % Column 1 of P(M1)               divided by its sum
        
        
    end
    
    
    
    % ------------------------------------------------------------------ % 
    % --------------------------- PLOTTING ----------------------------- % 
    % ------------------------------------------------------------------ % 
    %                Plotting iteratively all five models                % 
    % ------------------------------------------------------------------ % 
    
    % Prepare variables for plotting
    % P_S1_M1_O_plot = P_S1_M1_O;                                           % New placeholder variable for P(S1|M1,01)
    P_S1_O_plot = P_S1_O;                                                   % New placeholder variable for P(S1|O1)
    % P_M1_O_plot = P_M1_O;                                                 % New placeholder variable for P(M1|O1)
    
    % Expand posteriors for plotting purposes
    o=1;                                                                    % Indicator for observation
    for t=1:T                                                               % For loop across all time points T=80
        for tau=1:Tau                                                       % For loop across all trials Tau=2
        % P_S1_M1_O_plot(:,:,o) = P_S1_M1_O(:,:,t);                         % Turn ts into os for P(S1,M1|O1)
        P_S1_O_plot(:,o)        = P_S1_O(:,t);                              % Turn ts into os for P(S1|O1)
        % P_M1_O_plot(:,o)      = P_M1_O(:,t);                              % Turn ts into os for P(M1|O1)
        o=o+1;                                                              % Add 1 to observation
        end                                                                 
    end                                                                     
    
    % Posterior over outcomes
    Xo=P_O1_S1;                                                             % P(O1|S1)
    for o=1:Nobs                                                            % For loop from o=1 to all observations=160
        Xo(:,o) = P_O1_S1*P_S1_O_plot(:,o);                                 % Marginalise over s1: Likelihood (P(O1|S1)) * Marginal Posterior (states after obs: P(S1|O1))
    end
    
    % PLOT priors
    subplot(3,3,i);                                                         % Subplot: 3 rows, 3 columns, i=first (left) column
    if model==1
       h=bar(P_S1_M1(:,1));                                                 
       title('(A) Flexible negative prior belief (π_{b}=0.6)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I think I am not interesting')
    elseif model==2
       h=bar(P_S1_M1(:,2));
       title('(B) Overconfident negative prior belief (π_{b}=1.2)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I am sure I am not interesting')
    else
       h=bar(P_S1_M1(:,3));
       title('(C) Flexible negative prior belief (π_{b}=0.6)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I think I am not interesting')
    end
    ylim([0 1]); 
    h.FaceColor=[0.1000 0.4470 0.9000];
    h.FaceColor=[0 0.4470 0.7410];
    ylabel('\fontsize{8} P(B)')
    
    hold on
    
    % PLOT likelihoods
    subplot(3,3,[i+1]);                                                     % Subplot: 5 rows, 3 columns, i=two (right) columns
    if model==1
       for s1=1:NS1                                                         % For loop to create the (10x5) likelihood matrix: P(O1|S1)
           pdf = normpdf(O1, S1(s1), 1/0.6);                                % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
           P_O1_S1(:,s1) = pdf./sum(pdf);                                   % Normalize Gaussian by dividing each of its columns with its SUM
       end                                                                         
       h=bar(P_O1_S1(:,5));                                                 
       title('(A) Moderately weighted positive observation (π_{ο}=0.6)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Therapist Behaviour: My therapist thinks I am interesting')
    elseif model==2
       for s1=1:NS1                                                         % For loop to create the (10x5) likelihood matrix: P(O1|S1)
           pdf = normpdf(O1, S1(s1), 1/0.6);                                % Discrete Gaussian with μ=(S1) & σ=1/po1, representing each S1
           P_O1_S1(:,s1) = pdf./sum(pdf);                                   % Normalize Gaussian by dividing each of its columns with its SUM
       end                                                                         
       h=bar(P_O1_S1(:,5));
       title('(B) Moderately weighted positive observation (π_{ο}=0.6)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Therapist Behaviour: My therapist thinks I am interesting')
    else
       h=bar(P_O1_S1(:,5));
       title('(C) Strongly weighted positive observation (π_{ο}=1.2)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Therapist Behaviour: My therapist is sure I am interesting')
    end
    ylim([0 1]); 
    h.FaceColor=[0.9290 0.6940 0.1250];
    ylabel('\fontsize{8} P(O|B)')

    hold on
    
    % PLOT posteriors
    subplot(3,3,[i+2]);                                                     % Subplot: 5 rows, 3 columns, i=two (right) columns
    if model==1
       h=bar(P_S1_M1(:,1,t));                                                 
       title('(A) Flexible bimodal posterior belief (π_{b}=0.4)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I may or may not be interesting')
    elseif model==2
       h=bar(P_S1_M1(:,2,t));
       title('(B) Overconfident negative posterior belief (π_{b}=1.1)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I am sure I am not interesting')
    else
       h=bar(P_S1_M1(:,3,t));
       title('(C) Overconfident positive posterior belief (π_{b}=0.8)', ...
             'FontSize', 10)
       xlabel('\fontsize{8} Patient Belief: I might be interesting')
    end
    ylim([0 1]); 
    h.FaceColor=[0.4940 0.1840 0.5560];
    ylabel('\fontsize{8} P(B|O)')
    
    hold on
    
    i = i+3;                                                                % Add 3 to i to move to next row (after having filled 3 columns)
    o = 1;                                                                  % Initialize observations (for the next model)
    
    
end

% Get current figure handle
fig = gcf;

% Set figure units to inches (or centimeters)
fig.Units = 'inches';
fig.PaperUnits = 'inches';

% Define desired width and height (e.g., 12x6 inches)
width = 14;
height = 10;

% Adjust on-screen figure size
fig.Position(3:4) = [width, height];

% Configure paper settings
fig.PaperPositionMode = 'manual';
fig.PaperPosition = [0 0 width height];
fig.PaperSize = [width height];

% Set background color to white
fig.Color = 'white';            % White Background colour
fig.InvertHardcopy = 'off';     % Maintain existing colours
% fig.InvertHardcopy = 'off';   % Preserve background colour

% Save as PDF
print(fig, 'Figure 1.pdf', '-dpdf');

