



clear all
close all




% Observations
load S.mat;                                                                 % Load specific observations
o1=S(4).O1(1,:);                                                            % Positive to negative to positive again
o1=[o1 o1];                                                                 % Double the size of o1 to get more observations
o2=S(5).O1(1,:);                                                            % Positive to negative to positive again
o2=[o2 o2];                                                                 % Double the size of o2 to get more observations
% plot(o1);                                                                 % Plot (normally distributed) observations


% Lenghts for for loops
NO1 = max(o1);                                                              %   10    O1   outcomes
NO2 = max(o2);                                                              %   10    O2   outcomes
NS1 = 5;                                                                    %    5    S1   states (of the self)
NM1 = 4;                                                                    %    4    M1   models (of the self)
NS2 = 5;                                                                    %    5    S2   states (of the other)
NM2 = 4;                                                                    %    4    M1   models (of the other)
Tau = 2;                                                                    %    2   Tau   observations per trial
T =  length(o1)/2;                                                          %   80     T   trials
Nobs = length(o1);                                                          %  160    O1   observations (behaviours)


% Key parameters
eta   = [0.90  0.30  0.85  0.90];                                           % Learning rate (high = fast update of Dirichlet priors)
omega = [0.90  0.95  0.95  0.85];                                           % Forgetting rate (high = slow forgetting of Dirichlet priors)
ps1   = [0.30  0.30  0.30  1.00];                                           % Precision of P(s1|m1): Higher = internal self-mentalizing
ps2   = [0.30  0.30  0.30  1.00];                                           % Precision of P(s2|m2): Higher = internal other-mentalizing
po1   =  0.40;                                                              % Precision of P(o1|s1): Higher = external self-mentalizing
po2   =  0.40;                                                              % Precision of P(o2|s2): Higher = external other-mentalizing




% Hyperpriors: priors of mental states: P(s1|m1)
% (how mental states are generated by model of Self)
S1 = [0 3 5 7 10];                                                          % Values x at which to evaluate probability density function
% Hyperpriors: priors of mental states: P(s2|m2)
% (how mental states are generated by model of Other)
S2 = [0 3 5 7 10];                                                          % Values x at which to evaluate probability density function




% Get likelihoods
O1 = 1:1:max(o1);                                                           % Outcomes [1 2 3 4 5 6 7 8 9 10]
O2 = 1:1:max(o2);                                                           % Outcomes [1 2 3 4 5 6 7 8 9 10]
dmu=[0 0 0 0 0];                                                            % For this simulation, we assume dmu=0
dsig=0;
P_O1_S1S2 = nan(NO1, NS1, NS2);
P_O2_S2 = nan(NO2, NS2);
for s1=1:NS1                                                                % For loop to create (10x5x5) likelihood matrix P(O1|S1,S2)
    for s2=1:NS2                                                            % and 10x5 likelihood matrix P(O2|S2)
        % dmu = 5*(S2(s2)-5);                                               % External state shifts mean up or down
        % dsig = 0.1*abs((S2(s2)-5));                                       % External state also reduces precision
        pdf = normpdf(O1, S1(s1)+dmu(s2), 1/po1+dsig);                      % Discrete Gaussian (defining S1-S2 likelihood) with μ=S1+dmu & σ=1/po1+dsig
        P_O1_S1S2(:, s1, s2) = pdf./sum(pdf);                               % Normalize Gaussian by dividing each of its columns with its SUM
        P_O2_S2(:, s2)=normpdf(O2, S2(s2), 1/po2);                          % Discrete Gaussian (defining S2 likelihood) with μ=S2 & σ=1/po1+dsig
    end
end                                                                         % End result is 10x5 matrix representing all outcome-state mappings




i=1;                                                                        % Indicator of Figure position (see PLOTTING section at line 260)
FF=figure;

for model=1:5
    
    % --- CRITICAL RESET TO PREVENT CROSS-CONTAMINATION ---
    o=1;                                                                    % Indicator of which observation the agent experiences at trial t, time tau
    
    % Reset Hyperpriors exactly to initial state for each model pass
    prior_s1_m1 = []; prior_s2_m2 = [];
    prior_s1_m1(:, 1 ) = normpdf(S1,  1,  1/ps1(1));
    prior_s1_m1(:, 2 ) = normpdf(S1,  5,  1/ps1(2));                            
    prior_s1_m1(:, 3 ) = normpdf(S1,  9,  1/ps1(3));                            
    prior_s1_m1(:, 4 ) = [1.1 0.8 0.7 0.8 1.1];                                 
    
    prior_s2_m2(:, 1 ) = normpdf(S2,  1,  1/ps2(1));                            
    prior_s2_m2(:, 2 ) = normpdf(S2,  5,  1/ps2(2));                            
    prior_s2_m2(:, 3 ) = normpdf(S2,  9,  1/ps2(3));                            
    prior_s2_m2(:, 4 ) = [1.1 0.8 0.7 0.8 1.1];                                 
    
    P_S1_M11(:, 1 ) = prior_s1_m1(:, 1 )./sum(prior_s1_m1(:, 1 ));               
    P_S1_M11(:, 2 ) = prior_s1_m1(:, 2 )./sum(prior_s1_m1(:, 2 ));               
    P_S1_M11(:, 3 ) = prior_s1_m1(:, 3 )./sum(prior_s1_m1(:, 3 ));               
    P_S1_M11(:, 4 ) = prior_s1_m1(:, 4 )./sum(prior_s1_m1(:, 4 ));               
    P_S2_M22(:, 1 ) = prior_s2_m2(:, 1 )./sum(prior_s2_m2(:, 1 ));               
    P_S2_M22(:, 2 ) = prior_s2_m2(:, 2 )./sum(prior_s2_m2(:, 2 ));               
    P_S2_M22(:, 3 ) = prior_s2_m2(:, 3 )./sum(prior_s2_m2(:, 3 ));               
    P_S2_M22(:, 4 ) = prior_s2_m2(:, 4 )./sum(prior_s2_m2(:, 4 ));  
    
    % Preallocate trial variables
    P_S1_M1_O =  nan(NS1, NM1, T); P_S2_M2_O =  nan(NS2, NM2, T);
    P_S1_O    =  nan(NS1, T);      P_S2_O    =  nan(NS2, T);
    P_M1_O    =  nan(NM1, T);      P_M2_O    =  nan(NM2, T);
    Pr        =  nan(NS1, NS2, NM1); P_O_SM  =  nan(NS1, NM1, NM1);
    P_S1_M1   =  nan(NS1, NM1);      P_S2_M2   =  nan(NS2, NM2);

    if model==1                                                             % IF function to run through five models
       prior_m1 = [0 1 0 0];                                                % This allows only the  NORMAL  mental model to be active
       prior_m2 = [0 1 0 0];
       colour='cyan';
       o1=[S(6).O1(1,:) S(6).O1(1,:)];
       o2=[S(4).O1(1,:) S(4).O1(1,:)];                                      % Normative self-behaviours
       
    elseif model==2
       prior_m1 = [1 0 0 0];                                                % This allows only the NEGATIVE mental model to be active
       prior_m2 = [1 0 0 0];
       colour = [0.1000 0.4470 0.9000];
       o1=[S(1).O1(1,:) S(1).O1(1,:)];
       o2=[S(4).O1(1,:) S(4).O1(1,:)];                                      % Normative self-behaviours
    
    elseif model==3
       prior_m1 = [0 0 1 0];                                                % This allows only the POSITIVE mental model to be active
       prior_m2 = [0 0 1 0];                                                % This allows only the POSITIVE mental model to be active
       colour = [0.95 0 0];
       o1=[S(1).O1(1,:) S(1).O1(1,:)];
       o1=11-o1; 
       o2=[S(4).O1(1,:) S(4).O1(1,:)];                                      % Normative self-behaviours
    
    elseif model==4
       prior_m1 = [1 0 1 0];                                                % This allows both the NEGATIVE & POSITIVE models to be active (creating a SPLIT mental model)
       prior_m2 = [1 0 1 0];                                                % This allows both the NEGATIVE & POSITIVE models to be active (creating a SPLIT mental model)
       colour='black';
       o1=[S(3).O1(1,:) S(3).O1(1,:)];
       o2=[S(4).O1(1,:) S(4).O1(1,:)];                                      % Normative self-behaviours
    
    else
       prior_m1 = [0 0 0 1];                                                % This allows only the  EMPTY mental model to be active
       prior_m2 = [0 0 0 1];                                                % This allows only the  EMPTY mental model to be active
       colour='yellow';
       o1=[S(5).O1(1,:) S(5).O1(1,:)];
       o2=[S(4).O1(1,:) S(4).O1(1,:)];                                      % Normative self-behaviours
    
    end
    
    
    P_M1(:,1) = prior_m1./sum(prior_m1);                                    % Normalize distribution of mental model: P(M1)
    P_M2(:,1) = prior_m2./sum(prior_m2);                                    % Normalize distribution of mental model: P(M2)
    
    for m=1:NM2
        P_S2_M2(:, m)  = P_S2_M22(:, m)*P_M2(m);
        P_S1_M1(:, m)  = P_S1_M11(:, m)*P_M1(m);
    end
    
    
    for t=1:T                                                               % For loop from t=1 to T=40 (number of trials)
        
        % -------------------------------------------------------------- % 
        % ------------------------- INFERENCE -------------------------- % 
        % -------------------------------------------------------------- % 
        for tau=1:Tau                                                       % For loop from tau=1 to Tau=2 (number of observations per trial)
            
            for s2=1:NS2
                
                for m1=1:NM1                                                % For loop from m1=1 to NM1=4 (number of state configurations / hyperpriors)
                
                % PRIORS
                if tau==1                                                   % If-then function to create priors of states based on mental models: P(S1|M1)
                   Pr(:,s2,m1)  = P_S2_M2(s2,m1,t)*P_S1_M1(:,m1,t);         % For the first observation (at t=1 & tau=1) the prior is P(S2|M2)(*P(M2))*P(S1|M1)*(P(M1))
                else                                                        % For all other (tau) observations (in all other trials), 
                   Pr(:,s2,m1)  = P_S_O(:, s2, m1);                         % the prior is simply the previous posterior: P(S1,M1,S2,M2|O1,O2)
                end                                                         % Pr = Prior = 5x5x4 matrix = how states are under given self-other models
                
                % LIKELIHOODS
                P_O_SM(:,s2,m1) = P_O1_S1S2(o1(o),:,s2)*P_O2_S2(o2(o),s2);  % Likelihood of observations = P(O1|S1,S2) * P(O2|S2)
                
                end
                
            end
            
            % BAYESIAN INVERSION                                            % Use Bayes' rule to invert generative model and obtain P(S1,M1,S2,M2|O1,O2)
            P_J   = Pr.*P_O_SM;                                             % Bayes numerator: Joint probability: P(O1,S1,M1,O2,S2,M2)
            Po    = sum(P_J(:));                                            % Bayes denominator: Marinal probability: P(O1,O2)
            P_S_O = P_J./Po;                                                % Posterior: P(S1,M1,S2,M2|O1,O2) = Joint / Marginal = 10x4 matrix
            
            o=o+1;                                                          % Add 1 to the variable that indicates which observation is experienced at trial T, time tau
        
        end
        
        % Marginal posteriors at the end of the trial
        P_S1_M1_O(:,:,t) = squeeze(sum(P_S_O,2));                           % Squeeze the posterior at time t into a placeholder variable
        P_S2_M2_O(:,:,t) = squeeze(sum(P_S_O,1));                           % Squeeze the posterior at time t into a placeholder variable
        
        P_S1_O(:,t)      = sum(sum(P_S_O,3),2);                             % Sum rows of P(S1|O1,O2) (prob of S1 states given observations across all models)
        P_S2_O(:,t)      = sum(sum(P_S_O,3),1);                             % Sum rows of P(S2|O1,O2) (prob of S2 states given observations across all models)
        
        P_M1_O(:,t)      = squeeze(sum(sum(P_S_O,2),1));                    % Sum columns of P_S_O (prob of each model being endorsed based on state likelihood)
        
        
        % -------------------------------------------------------------- %
        % ------------------------- LEARNING --------------------------- %
        % -------------------------------------------------------------- %
        
        if model==1
           prior_s1_m1(:,2) = omega(2)*prior_s1_m1(:,2) + ...               % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                              eta(2)*P_S1_M1_O(:,2,t);
           prior_s2_m2(:,2) = omega(2)*prior_s2_m2(:,2) + ...               % Dirichlet prior denoting P(S2|M2=NEGATIVE)
                              eta(2)*P_S2_M2_O(:,2,t);
           P_S1_M1(:, 2, t+1) = prior_s1_m1(:, 2)/sum(prior_s1_m1(:,2),1);  % Column 1 of P(S1|M1=NEGATIVE)   divided by its sum
           P_S2_M2(:, 2, t+1) = prior_s2_m2(:, 2)/sum(prior_s2_m2(:,2),1);  % Column 1 of P(S2|M2=NEGATIVE)   divided by its sum
           
        elseif model==2
               prior_s1_m1(:,1) = omega(1)*prior_s1_m1(:,1) + ...           % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                                  eta(1)*P_S1_M1_O(:,1,t);
               prior_s2_m2(:,1) = omega(1)*prior_s2_m2(:,1) + ...                  % Dirichlet prior denoting P(S2|M2=NEGATIVE)
                                  eta(1)*P_S2_M2_O(:,1,t);
               P_S1_M1(:, 1, t+1) = prior_s1_m1(:, 1)/sum(prior_s1_m1(:,1),1);     % Column 1 of P(S1|M1=NEGATIVE)   divided by its sum
               P_S2_M2(:, 1, t+1) = prior_s2_m2(:, 1)/sum(prior_s2_m2(:,1),1);     % Column 1 of P(S2|M2=NEGATIVE)   divided by its sum
               if t==80
                  prior_s1_m1(:, 1 ) = normpdf(S1,  1,  1/ps1(1));          % Discrete Gaussian with μ=01 & σ=1/ps1, reflecting states under  NEGATIVE  mental model
                  prior_s2_m2(:, 1 ) = normpdf(S2,  1,  1/ps2(1));          % Discrete Gaussian with μ=01 & σ=1/ps1, reflecting states under  NEGATIVE  mental model
                  P_S1_M1(:, 1 ) = prior_s1_m1(:, 1 )./sum(prior_s1_m1(:, 1 )); % P(S1|M1) = States under  NEGATIVE  model
                  P_S2_M2(:, 1 ) = prior_s2_m2(:, 1 )./sum(prior_s2_m2(:, 1 )); % P(S2|M2) = States under  NEGATIVE  model
               end
        
        elseif model==3
               prior_s1_m1(:,3) = omega(3)*prior_s1_m1(:,3) + ...           % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                                  eta(3)*P_S1_M1_O(:,3,t);
               prior_s2_m2(:,3) = omega(3)*prior_s2_m2(:,3) + ...           % Dirichlet prior denoting P(S2|M2=NEGATIVE)
                                  eta(3)*P_S2_M2_O(:,3,t);
               P_S1_M1(:, 3, t+1) = prior_s1_m1(:, 3)/sum(prior_s1_m1(:,3),1); % Column 1 of P(S1|M1=NEGATIVE)   divided by its sum
               P_S2_M2(:, 3, t+1) = prior_s2_m2(:, 3)/sum(prior_s2_m2(:,3),1); % Column 1 of P(S2|M2=NEGATIVE)   divided by its sum
               if t==80
                  prior_s1_m1(:, 3 ) = normpdf(S1,  9,  1/ps1(3));          % Discrete Gaussian with μ=09 & σ=1/ps1, reflecting states under  POSITIVE  mental model
                  prior_s2_m2(:, 3 ) = normpdf(S2,  9,  1/ps2(3));          % Discrete Gaussian with μ=09 & σ=1/ps1, reflecting states under  POSITIVE  mental model
                  P_S1_M1(:, 3 ) = prior_s1_m1(:, 3 )./sum(prior_s1_m1(:, 3 )); % P(S1|M1) = States under  POSITIVE  model
                  P_S2_M2(:, 3 ) = prior_s2_m2(:, 3 )./sum(prior_s2_m2(:, 3 )); % P(S2|M2) = States under  POSITIVE  model
               end
        
        elseif model==4
               prior_s1_m1(:,1) = omega(1)*prior_s1_m1(:,1) + ...           % Dirichlet prior denoting P(S1|M1=NEGATIVE)
                                  eta(1)*P_S1_M1_O(:,1,t);
               prior_s1_m1(:,3) = omega(1)*prior_s1_m1(:,3) + ...           % Dirichlet prior denoting P(S1|M1=POSITIVE)
                                  eta(1)*P_S1_M1_O(:,3,t);
               prior_s2_m2(:,1) = omega(1)*prior_s2_m2(:,1) + ...           % Dirichlet prior denoting P(S2|M2=NEGATIVE)
                                  eta(1)*P_S2_M2_O(:,1,t);
               prior_s2_m2(:,3) = omega(1)*prior_s2_m2(:,3) + ...           % Dirichlet prior denoting P(S3|M3=POSITIVE)
                                  eta(1)*P_S2_M2_O(:,3,t);
               P_S1_M1(:, 1, t+1) = prior_s1_m1(:, 1)/sum(prior_s1_m1(:,1),1); % Column 2 of P(S1|M1=NEGATIVE) divided by its sum
               P_S1_M1(:, 3, t+1) = prior_s1_m1(:, 3)/sum(prior_s1_m1(:,3),1); % Column 3 of P(S1|M1=POSITIVE) divided by its sum
               P_S2_M2(:, 1, t+1) = prior_s2_m2(:, 1)/sum(prior_s2_m2(:,1),1); % Column 2 of P(S2|M2=NEGATIVE) divided by its sum
               P_S2_M2(:, 3, t+1) = prior_s2_m2(:, 3)/sum(prior_s2_m2(:,3),1); % Column 3 of P(S2|M2=POSITIVE) divided by its sum
        
         elseif model==5
                prior_s1_m1(:,4) = omega(4)*prior_s1_m1(:,4) + ...          % Dirichlet prior denoting P(S1|M1=EMPTY)
                                   eta(4)*P_S1_M1_O(:,4,t);
                prior_s2_m2(:,4) = omega(4)*prior_s2_m2(:,4) + ...          % Dirichlet prior denoting P(S4|M4=EMPTY)
                                   eta(4)*P_S2_M2_O(:,4,t);
                P_S1_M1(:, 4, t+1) = prior_s1_m1(:, 4)/sum(prior_s1_m1(:,4),1); % Column 4 of P(S1|M1=EMPTY)      divided by its sum
                P_S2_M2(:, 4, t+1) = prior_s2_m2(:, 4)/sum(prior_s2_m2(:,4),1); % Column 4 of P(S2|M2=EMPTY)      divided by its sum
         end
        
    end
    
    
    % ------------------------------------------------------------------ %
    % --------------------------- PLOTTING ----------------------------- %
    % ------------------------------------------------------------------ %
    % Prepare variables for plotting
    P_S1_O_plot = P_S1_O;                                                   % New placeholder variable for P(S1|O1)
    P_S2_O_plot = P_S2_O;                                                   % New placeholder variable for P(S2|O2)
    % Expand posteriors for plotting purposes
    o_idx=1;                                                                % Using a safe unique variable name to prevent overwrite
    for t_plot=1:T                                                          % For loop across all time points T=80
        for tau_plot=1:Tau                                                  % For loop across all trials Tau=2
            P_S1_O_plot(:,o_idx)        = P_S1_O(:,t_plot);                 % Turn ts into os for P(S1|O1)
            P_S2_O_plot(:,o_idx)        = P_S2_O(:,t_plot);
            o_idx=o_idx+1;                                                  % Add 1 to observation
        end
    end
    
    % Posterior over outcomes
    xo=nan(NO1, NS1);                                                       % Likelihoods P(O1|S1)
    Xo=nan(NO1, NS1);                                                       % Likelihoods P(O1|S1)
    for o_p=1:Nobs                                                          % For loop from o=1 to all observations=160
        for s1=1:NS1
            xo(:,s1) = squeeze(P_O1_S1S2(:,s1,:))*P_S2_O_plot(:,o_p);       % Multiply each column P(O1|S1,S2) to P(S2|O1,O2)
        end
        Xo(:,o_p) = xo*P_S1_O_plot(:,o_p);                                  % Marginalise over s1: Likelihood * Marginal Posterior
    end
    % Find posterior prediction
    a=NaN(1,160);                                                           % Initialize a: posterior prediction
    for o_p=1:Nobs                                                          % For loop across all observations = 160
        [~, a(:,o_p)] = max(Xo(:,o_p));                                     % Safe fix: Uses Max to prevent NaN crashing while preserving accurate location index
    end                                                                     % End result = 1x160 indicating posterior predictions
    
    % PLOT models
    subplot(5,4,i);                                                         % Subplot: 5 rows, 3 columns, i=first (left) column
    if model==1
       h=bar(P_S1_M11(:,2));
       title('(A) Neutral starting model (π_{m}=0.3, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==2
       h=bar(P_S1_M11(:,1));
       title('(B) Semi-Negative starting model (π_{m}=0.3, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==3
       h=bar(P_S1_M11(:,3));
       title('(C) Semi-Positive starting model (π_{m}=0.3, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==4
       h=bar(P_S1_M11(:,1)); h.FaceColor=colour; hold on
       h=bar(P_S1_M11(:,3));
       title('(D) Semi-Split starting model (π_{m}=0.3, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    else
       h=bar(P_S1_M11(:,4));
       title('(E) Semi-Empty starting model (π_{m}=0.3, π_{ο}=0.4)', ...
             'FontSize', 8.5)
       xlabel('\fontsize{7} States')
    end
    ylim([0 1]);
    h.FaceColor=colour;
    ylabel('\fontsize{7} P(S1|M1)')
    
    hold on
    
    % PLOT posteriors
    subplot(5,4,[i+1 i+2]);                                                 % Subplot: 5 rows, 3 columns, i=two (right) columns
    plot(o1,'ko', 'Color','k', ...
        'Markersize',8, ...
         MarkerFaceColor=[.8 .8 .8]); hold on;
    plot(a(:,:),'ko', 'Color','k', 'Markersize',6, MarkerFaceColor=colour);
    hold on; ylim([0 11]);
    
    if model==1
       title('(A) Mental inferences under neutral model (cyan circles) and integrative observations (grey circles)')
    elseif model==2
       title('(B) Mental inferences under semi-negative model (blue circles) and negative observations (grey circles)')
    elseif model==3
       title('(C) Mental inferences under semi-positive model (red circles) and positive observations (grey circles)')
    elseif model==4
       title('(D) Mental inferences under semi-split model (black circles) and dichotomous observations (grey circles)')
    else
       title('(E) Mental inferences under semi-empty model (yellow circles) and disorganized observations (grey circles)')
       xlabel('\fontsize{7} Trial')
    end
    
    ylabel('\fontsize{7} Observation')
    
    % PLOT FINAL models
    subplot(5,4,i+3);                                                       % Subplot: 5 rows, 3 columns, i=first column (on the left)
    if model==1
       prior_s1_m1_F(:,2) = normpdf(S1, 5, 1/0.9);
       P_S1_M1_F(:,2) = prior_s1_m1_F(:,2)./sum(prior_s1_m1_F(:,2));
       h=bar(P_S1_M1_F(:,2));
       title('(A) Integrated final model (π_{m}=0.9, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==2
       prior_s1_m1_F(:,1) = normpdf(S1, 1, 1/0.9);
       P_S1_M1_F(:,1) = prior_s1_m1_F(:,1)./sum(prior_s1_m1_F(:,1));
       h=bar(P_S1_M1_F(:,1));
       title('(B) Negative final model (π_{m}=0.9, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==3
       prior_s1_m1_F(:,3) = normpdf(S1, 9, 1/0.9);
       P_S1_M1_F(:,3) = prior_s1_m1_F(:,3)./sum(prior_s1_m1_F(:,3));
       h=bar(P_S1_M1_F(:,3));
       title('(C) Positive final model (π_{m}=0.9, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    elseif model==4
       prior_s1_m1_F(:,1) = normpdf(S1, 1, 1/1);
       P_S1_M1_F(:,1) = prior_s1_m1_F(:,1)./sum(prior_s1_m1_F(:,1));
       h=bar(P_S1_M1_F(:,1)); h.FaceColor=colour; 
       hold on
       
       prior_s1_m1_F(:,3) = normpdf(S1, 9, 1/0.90);
       P_S1_M1_F(:,3) = prior_s1_m1_F(:,3)./sum(prior_s1_m1_F(:,3));
       h=bar(P_S1_M1_F(:,3)); 
       title('(D) Semi-Split final model (π_{m}=0.9, π_{ο}=0.4)', ...
             'FontSize', 8.5)
    else
       P_S1_M1_F(:,4) = [0.20 0.20 0.2 0.2 0.2];                            
       h=bar(P_S1_M1_F(:,4));
       title('(E) Empty final model (π_{m}=0, π_{ο}=0.4)', ...
             'FontSize', 8.5)
       xlabel('\fontsize{7} States')
    end
    ylim([0 1]);
    h.FaceColor=colour;
    ylabel('\fontsize{7} P(S1|M1)')
    
    hold on
    
    i = i+4;                                                                % Add 4 to i to move to next row (after having filled 4 columns)
    
end

% Get current figure handle
fig = gcf;

% Set figure units to inches (or centimeters)
fig.Units = 'inches';
fig.PaperUnits = 'inches';

% Define desired width and height (e.g., 12x6 inches)
width = 16;
height = 10;

% Adjust on-screen figure size
fig.Position(3:4) = [width, height];

% Configure paper settings
fig.PaperPositionMode = 'manual';
fig.PaperPosition = [0 0 width height];
fig.PaperSize = [width height];

% Set background color to white
fig.Color = 'white';            % White Background colour
fig.InvertHardcopy = 'off';     % Maintain existing colours

% Save as PDF
print(fig, 'Figure 6.pdf', '-dpdf');


